import type { AssessmentQuestion, CareerDomainId } from "./types";

/**
 * Adaptive assessment question bank — PRD §3.1 FR-TAL-02.
 * Each career has 10 Technical + 3 Soft-Skill questions (13 total).
 * ponytail: static bank; replace with DB-backed adaptive engine at scale.
 */
export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  // ── Frontend Dev (10 Technical + 3 Soft Skills) ───────────
  {
    id: "fe-html-1",
    careerId: "frontend-dev",
    type: "TECHNICAL",
    skillId: "html",
    text: "Apa fungsi utama atribut `alt` pada elemen <img>?",
    options: [
      { label: "Menampilkan tooltip saat kursor hover di atas gambar", score: 30 },
      { label: "Menyediakan teks alternatif untuk aksesibilitas screen reader dan fallback gambar", score: 100 },
      { label: "Menentukan ukuran file gambar di browser", score: 10 },
      { label: "Mengatur posisi gambar dalam layout halaman", score: 10 },
    ],
  },
  {
    id: "fe-css-1",
    careerId: "frontend-dev",
    type: "TECHNICAL",
    skillId: "css",
    text: "Kapan sebaiknya memilih CSS Grid dibandingkan Flexbox?",
    options: [
      { label: "Saat ingin mengatur layout 2 dimensi (baris dan kolom sekaligus)", score: 100 },
      { label: "Flexbox dan Grid identik, hanya beda nama sintaks", score: 10 },
      { label: "Grid hanya digunakan untuk tabel data tabular", score: 20 },
      { label: "Hanya saat memerlukan animasi transisi CSS", score: 10 },
    ],
  },
  {
    id: "fe-js-1",
    careerId: "frontend-dev",
    type: "TECHNICAL",
    skillId: "javascript",
    text: "Apa perbedaan mendasar antara `==` dan `===` di JavaScript?",
    options: [
      { label: "`==` membandingkan nilai dan tipe data tanpa konversi tipe", score: 20 },
      { label: "`===` membandingkan nilai dan tipe data sekaligus tanpa type coercion otomatis", score: 100 },
      { label: "Keduanya bekerja persis sama pada tipe string dan angka", score: 10 },
      { label: "`===` hanya dapat digunakan untuk perbandingan object dan array", score: 0 },
    ],
  },
  {
    id: "fe-react-1",
    careerId: "frontend-dev",
    type: "TECHNICAL",
    skillId: "react",
    text: "Kapan cleanup function pada React `useEffect` dijalankan?",
    options: [
      { label: "Saat komponen pertama kali di-mount ke DOM", score: 10 },
      { label: "Sebelum re-run effect berikutnya dan saat komponen unmount dari DOM", score: 100 },
      { label: "Hanya saat seluruh aplikasi ditutup oleh user", score: 10 },
      { label: "Setiap kali ada pembaruan DOM tanpa memicu effect", score: 20 },
    ],
  },
  {
    id: "fe-tailwind-1",
    careerId: "frontend-dev",
    type: "TECHNICAL",
    skillId: "tailwind",
    text: "Bagaimana cara kerja prinsip Mobile-First pada breakpoint Tailwind CSS?",
    options: [
      { label: "Class tanpa prefix berlaku untuk mobile, prefix seperti `md:` berlaku di ukuran tersebut ke atas", score: 100 },
      { label: "Class prefix `sm:` hanya berlaku untuk layar ukuran desktop besar", score: 20 },
      { label: "Tailwind mewajibkan penulisan file terpisah per ukuran layar", score: 0 },
      { label: "Ukuran mobile harus selalu didefinisikan dengan prefix khusus `mobile:`", score: 10 },
    ],
  },
  {
    id: "fe-nextjs-1",
    careerId: "frontend-dev",
    type: "TECHNICAL",
    skillId: "nextjs",
    text: "Apa keuntungan utama React Server Components (RSC) di Next.js App Router?",
    options: [
      { label: "Semua interaktivitas browser dapat ditangani tanpa JavaScript di client", score: 30 },
      { label: "Mengurangi client JavaScript bundle dan memungkinkan akses data langsung di server", score: 100 },
      { label: "Menggantikan seluruh kebutuhan CSS dan Tailwind", score: 0 },
      { label: "Membuat aplikasi otomatis berjalan secara offline", score: 10 },
    ],
  },
  {
    id: "fe-responsive-1",
    careerId: "frontend-dev",
    type: "TECHNICAL",
    skillId: "responsive-design",
    text: "Apa fungsi tag meta viewport `<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">`?",
    options: [
      { label: "Menyesuaikan lebar canvas visual render browser dengan lebar fisik perangkat pengguna", score: 100 },
      { label: "Mempercepat loading aset gambar di layar mobile", score: 20 },
      { label: "Mengunci orientasi layar ke mode portrait saja", score: 10 },
      { label: "Menghapus kebutuhan media query di file stylesheet", score: 0 },
    ],
  },
  {
    id: "fe-perf-1",
    careerId: "frontend-dev",
    type: "TECHNICAL",
    skillId: "web-performance",
    text: "Apa metrik Core Web Vitals yang mengukur kestabilan visual layout (mencegah elemen melompat saat render)?",
    options: [
      { label: "Cumulative Layout Shift (CLS)", score: 100 },
      { label: "Largest Contentful Paint (LCP)", score: 30 },
      { label: "First Input Delay (FID)", score: 20 },
      { label: "Time to First Byte (TTFB)", score: 10 },
    ],
  },
  {
    id: "fe-ts-1",
    careerId: "frontend-dev",
    type: "TECHNICAL",
    skillId: "typescript",
    text: "Mengapa tipe `unknown` lebih direkomendasikan daripada `any` di TypeScript saat menangani input tak terduga?",
    options: [
      { label: "`unknown` memaksa type-checking atau narrowing sebelum nilai tersebut dapat digunakan", score: 100 },
      { label: "`unknown` menonaktifkan semua validasi compiler TypeScript", score: 0 },
      { label: "`unknown` otomatis mengonversi data string ke tipe integer", score: 10 },
      { label: "`unknown` hanya bisa digunakan untuk object kosong `{}`", score: 20 },
    ],
  },
  {
    id: "fe-git-1",
    careerId: "frontend-dev",
    type: "TECHNICAL",
    skillId: "git",
    text: "Apa langkah yang tepat jika terjadi merge conflict saat menggabungkan branch fitur?",
    options: [
      { label: "Menghapus folder .git lalu inisialisasi ulang repositori", score: 0 },
      { label: "Meninjau file berkonflik, menyelesaikan konflik penanda git, lalu commit hasil resolusi", score: 100 },
      { label: "Memaksa push dengan flag --force ke branch utama", score: 10 },
      { label: "Mengabaikan konflik dan membiarkan penanda `<<<<<<<` di file produksi", score: 0 },
    ],
  },
  {
    id: "ss-problem-1",
    careerId: "frontend-dev",
    type: "SOFT_SKILL",
    skillId: "problem-solving",
    text: "Saat user melaporkan bug UI di browser mobile tertentu, langkah penanganan pertama Anda?",
    options: [
      { label: "Mengidentifikasi detail versi perangkat/browser dan mereproduksi bug secara konsisten sebelum menulis patch", score: 100 },
      { label: "Langsung menulis ulang seluruh komponen UI dari awal tanpa debug", score: 10 },
      { label: "Mengabaikan laporan jika tidak terjadi di laptop pribadi Anda", score: 0 },
      { label: "Menyarankan pengguna untuk tidak menggunakan browser tersebut", score: 10 },
    ],
  },
  {
    id: "ss-comm-1",
    careerId: "frontend-dev",
    type: "SOFT_SKILL",
    skillId: "communication",
    text: "Bagaimana cara menyampaikan hambatan teknis yang berpotensi menunda tenggat waktu ke pemilik UMKM?",
    options: [
      { label: "Menghubungi lebih awal, menjelaskan dampak dalam bahasa praktis, serta menawarkan opsi alternatif solusi", score: 100 },
      { label: "Menunggu hingga hari tenggat waktu lalu mengabarkan bahwa fitur belum selesai", score: 0 },
      { label: "Menggunakan jargon teknis rumit agar pemilik usaha merasa minder dan memaklumi", score: 10 },
      { label: "Mengurangi fitur secara diam-diam tanpa memberitahu siapapun", score: 10 },
    ],
  },
  {
    id: "ss-digital-1",
    careerId: "frontend-dev",
    type: "SOFT_SKILL",
    skillId: "digital-literacy",
    text: "Apa praktik keamanan digital dasar saat mengelola repositori kode proyek UMKM?",
    options: [
      { label: "Jangan commit file `.env` atau credential/API key ke repositori git publik", score: 100 },
      { label: "Menyimpan seluruh password database langsung di dalam file `README.md`", score: 0 },
      { label: "Menggunakan password yang sama untuk seluruh tools dan email", score: 10 },
      { label: "Membagikan akses admin git kepada siapa saja tanpa izin", score: 0 },
    ],
  },

  // ── UI/UX Designer (10 Technical + 3 Soft Skills) ─────────
  {
    id: "ux-figma-1",
    careerId: "ui-ux-designer",
    type: "TECHNICAL",
    skillId: "figma",
    text: "Apa fungsi utama fitur Auto Layout pada Figma?",
    options: [
      { label: "Membuat frame responsif yang padding dan spacing-nya otomatis menyesuaikan konten", score: 100 },
      { label: "Mengubah gambar bitmap menjadi vektor secara instan", score: 10 },
      { label: "Menerjemahkan teks bahasa asing otomatis", score: 0 },
      { label: "Mengompresi resolusi file desain menjadi SVG kecil", score: 20 },
    ],
  },
  {
    id: "ux-research-1",
    careerId: "ui-ux-designer",
    type: "TECHNICAL",
    skillId: "user-research",
    text: "Kapan metode kualitatif (misal in-depth interview) paling tepat digunakan?",
    options: [
      { label: "Saat ingin memahami motivasi mendalam, latar belakang masalah, dan 'mengapa' user bertindak", score: 100 },
      { label: "Saat membutuhkan angka persentase statistik jutaan pengunjung web", score: 20 },
      { label: "Saat menghitung conversion rate checkout ecommerce", score: 10 },
      { label: "Interview tidak pernah berguna dalam proses perancangan produk", score: 0 },
    ],
  },
  {
    id: "ux-wireframe-1",
    careerId: "ui-ux-designer",
    type: "TECHNICAL",
    skillId: "wireframing",
    text: "Mengapa wireframe low-fidelity penting sebelum membuat visual desain high-fidelity?",
    options: [
      { label: "Memvalidasi hierarki informasi dan alur navigasi cepat tanpa terdistraksi warna dan visual", score: 100 },
      { label: "Agar desainer tidak perlu membuat prototipe interaktif", score: 10 },
      { label: "Sebagai pengganti dokumen kontrak legal dengan klien", score: 0 },
      { label: "Hanya untuk memperbanyak jumlah file portofolio", score: 10 },
    ],
  },
  {
    id: "ux-prototype-1",
    careerId: "ui-ux-designer",
    type: "TECHNICAL",
    skillId: "prototyping",
    text: "Apa manfaat utama membuat clickable interactive prototype sebelum tahap koding?",
    options: [
      { label: "Menguji interaksi dan alur tugas user secara nyata sehingga memangkas revisi mahal di tahap koding", score: 100 },
      { label: "Otomatis menghasilkan kode produksi backend yang bebas bug", score: 10 },
      { label: "Menghilangkan kebutuhan evaluasi dan testing produk", score: 0 },
      { label: "Hanya untuk pamer estetika di media sosial desainer", score: 10 },
    ],
  },
  {
    id: "ux-ds-1",
    careerId: "ui-ux-designer",
    type: "TECHNICAL",
    skillId: "design-system",
    text: "Apa peran Design Tokens (color, typography, spacing) dalam Design System modern?",
    options: [
      { label: "Menyediakan variabel nilai desain terpusat yang dapat disinkronkan antara desainer dan developer", score: 100 },
      { label: "Membayar royalti penggunaan font berbayar di Figma", score: 0 },
      { label: "Mengunci file desain agar tidak bisa diedit orang lain", score: 10 },
      { label: "Menghapus komponen UI yang tidak dipakai di kanvas", score: 20 },
    ],
  },
  {
    id: "ux-usability-1",
    careerId: "ui-ux-designer",
    type: "TECHNICAL",
    skillId: "usability-testing",
    text: "Saat melakukan Usability Testing, sikap penguji (moderator) yang benar adalah?",
    options: [
      { label: "Mengamati alur partisipan, tidak mengarahkan jawaban, dan mendengarkan 'think-aloud'", score: 100 },
      { label: "Membimbing user menekan tombol yang tepat setiap kali user bingung", score: 10 },
      { label: "Menyalahkan user jika mereka gagal menyelesaikan skenario pengujian", score: 0 },
      { label: "Mengisi tugas pengujian sendiri agar waktu pengujian lebih cepat", score: 0 },
    ],
  },
  {
    id: "ux-ia-1",
    careerId: "ui-ux-designer",
    type: "TECHNICAL",
    skillId: "information-architecture",
    text: "Apa tujuan utama penataan Information Architecture (IA) pada website katalog produk UMKM?",
    options: [
      { label: "Memudahkan pengunjung menemukan kategori produk dan alur navigasi secara intuitif", score: 100 },
      { label: "Menyembunyikan harga barang agar calon pembeli harus chat WhatsApp terlebih dahulu", score: 10 },
      { label: "Membuat menu navigasi sebanyak dan serumit mungkin", score: 0 },
      { label: "Menyesuaikan ukuran gambar katalog dengan resolusi kamera", score: 20 },
    ],
  },
  {
    id: "ux-hierarchy-1",
    careerId: "ui-ux-designer",
    type: "TECHNICAL",
    skillId: "visual-hierarchy",
    text: "Bagaimana desainer menciptakan Visual Hierarchy yang kuat pada landing page?",
    options: [
      { label: "Menggunakan kontras skala font, bobot warna, white-space, dan peletakan strategis CTA", score: 100 },
      { label: "Membuat semua tulisan berukuran 24px dan bold agar terbaca jelas", score: 10 },
      { label: "Menghilangkan ruang kosong (white-space) agar halaman penuh padat", score: 0 },
      { label: "Menggunakan warna pelangi yang berbeda pada setiap kalimat", score: 0 },
    ],
  },
  {
    id: "ux-wcag-1",
    careerId: "ui-ux-designer",
    type: "TECHNICAL",
    skillId: "accessibility-design",
    text: "Berapa rasio kontras minimum yang disyaratkan WCAG 2.1 Level AA untuk teks berukuran normal?",
    options: [
      { label: "4.5 : 1", score: 100 },
      { label: "2.0 : 1", score: 20 },
      { label: "1.2 : 1", score: 0 },
      { label: "10 : 1", score: 40 },
    ],
  },
  {
    id: "ux-mobile-1",
    careerId: "ui-ux-designer",
    type: "TECHNICAL",
    skillId: "mobile-design",
    text: "Berapa ukuran area sentuh (touch target size) minimum yang disarankan untuk tombol di layar mobile?",
    options: [
      { label: "Minimal 44 × 44 pt / 48 × 48 dp", score: 100 },
      { label: "16 × 16 px", score: 10 },
      { label: "200 × 200 px", score: 20 },
      { label: "Bebas, tidak ada standar ukuran jari di mobile", score: 0 },
    ],
  },
  {
    id: "ss-problem-2",
    careerId: "ui-ux-designer",
    type: "SOFT_SKILL",
    skillId: "problem-solving",
    text: "Ketika pemilik UMKM meminta fitur yang menurut data riset tidak dibutuhkan pengguna mereka, apa yang Anda lakukan?",
    options: [
      { label: "Mendengarkan aspirasi bisnis pemilik, menyajikan temuan riset pengguna dengan santun, lalu merumuskan jalan tengah", score: 100 },
      { label: "Menolak mentah-mentah dan meremehkan pemahaman pemilik UMKM", score: 0 },
      { label: "Menuruti semua permintaan tanpa memberi masukan profesional apapun", score: 20 },
      { label: "Keluar dari proyek tanpa konfirmasi", score: 0 },
    ],
  },
  {
    id: "ss-comm-2",
    careerId: "ui-ux-designer",
    type: "SOFT_SKILL",
    skillId: "communication",
    text: "Bagaimana cara melakukan design handoff yang efektif kepada frontend developer?",
    options: [
      { label: "Memberikan file Figma rapi ber-Auto Layout, specs token, flow interaksi, dan sesi walkthrough singkat", score: 100 },
      { label: "Hanya mengirim screenshot JPG beresolusi rendah via WhatsApp", score: 0 },
      { label: "Menuntut developer menjiplak desain tanpa membuka ruang diskusi kendala teknis", score: 10 },
      { label: "Tidak mendokumentasikan state kosong (empty state) maupun state error", score: 10 },
    ],
  },
  {
    id: "ss-digital-2",
    careerId: "ui-ux-designer",
    type: "SOFT_SKILL",
    skillId: "digital-literacy",
    text: "Apa etika penggunaan aset visual (foto, ilustrasi, font) dalam proyek digital?",
    options: [
      { label: "Memastikan lisensi komersial aset jelas (Creative Commons / Free for Commercial / berlisensi resmi)", score: 100 },
      { label: "Mengambil gambar apa saja dari Google Images dengan watermark", score: 0 },
      { label: "Menggunakan font berbayar bajakan untuk aplikasi publik", score: 0 },
      { label: "Mengklaim hasil karya desainer lain sebagai portofolio pribadi", score: 0 },
    ],
  },

  // ── Data Analyst (10 Technical + 3 Soft Skills) ───────────
  {
    id: "da-sql-1",
    careerId: "data-analyst",
    type: "TECHNICAL",
    skillId: "sql",
    text: "Apa perbedaan antara klausa `WHERE` dan `HAVING` pada query SQL?",
    options: [
      { label: "`WHERE` menyaring baris sebelum grouping, sedangkan `HAVING` menyaring hasil fungsi agregasi setelah `GROUP BY`", score: 100 },
      { label: "`HAVING` dan `WHERE` dapat saling menggantikan tanpa perbedaan fungsi", score: 10 },
      { label: "`WHERE` hanya bisa dipakai untuk kolom bertipe tanggal", score: 0 },
      { label: "`HAVING` dieksekusi lebih dulu sebelum tabel dimuat", score: 10 },
    ],
  },
  {
    id: "da-python-1",
    careerId: "data-analyst",
    type: "TECHNICAL",
    skillId: "python",
    text: "Method Pandas mana yang paling efisien untuk menggabungkan dua DataFrame berdasarkan kolom kunci relasi?",
    options: [
      { label: "`pd.merge(df1, df2, on='key', how='inner')`", score: 100 },
      { label: "Menggunakan loop baris manual `for i in range(len(df1))`", score: 20 },
      { label: "`df1 + df2`", score: 0 },
      { label: "`pd.read_csv()`", score: 10 },
    ],
  },
  {
    id: "da-excel-1",
    careerId: "data-analyst",
    type: "TECHNICAL",
    skillId: "excel",
    text: "Apa keunggulan utama fungsi `XLOOKUP` dibandingkan `VLOOKUP` di Excel spreadsheet modern?",
    options: [
      { label: "Mendukung pencarian ke kiri tanpa batasan kolom acuan, default exact match, dan anti-rusak jika kolom bertambah", score: 100 },
      { label: "`XLOOKUP` hanya bisa menghitung rata-rata nilai angka", score: 10 },
      { label: "Tidak ada perbedaan, hanya penggantian nama fungsi", score: 10 },
      { label: "`VLOOKUP` lebih cepat pada jutaan baris data", score: 20 },
    ],
  },
  {
    id: "da-analytics-1",
    careerId: "data-analyst",
    type: "TECHNICAL",
    skillId: "analytics",
    text: "Bagaimana cara mendeteksi tren musiman (seasonality) pada data transaksi bulanan toko UMKM?",
    options: [
      { label: "Menganalisis perbandingan YoY (Year-over-Year) dan moving average 3-6 bulanan", score: 100 },
      { label: "Hanya melihat total omzet satu minggu terakhir saja", score: 20 },
      { label: "Menghapus semua data bulan yang penjualannya rendah", score: 0 },
      { label: "Menyimpulkan penjualan tanpa melihat grafik historis", score: 0 },
    ],
  },
  {
    id: "da-viz-1",
    careerId: "data-analyst",
    type: "TECHNICAL",
    skillId: "visualization",
    text: "Tipe grafik mana yang paling tepat untuk memperlihatkan tren pendapatan bisnis dari waktu ke waktu?",
    options: [
      { label: "Line chart (grafik garis deret waktu)", score: 100 },
      { label: "Pie chart dengan 20 irisan kecil", score: 10 },
      { label: "Radar chart", score: 20 },
      { label: "Scatter plot tanpa sumbu waktu", score: 30 },
    ],
  },
  {
    id: "da-clean-1",
    careerId: "data-analyst",
    type: "TECHNICAL",
    skillId: "data-cleaning",
    text: "Bagaimana penanganan yang tepat terhadap data duplikat dan missing value (NaN) dalam analisis transaksi?",
    options: [
      { label: "Mengidentifikasi akar penyebab missing data, mengisi imputasi bila valid, atau memfilter duplikasi transaksi", score: 100 },
      { label: "Mengisi seluruh sel kosong dengan angka 999999", score: 0 },
      { label: "Menghapus seluruh kolom begitu ada satu sel kosong", score: 10 },
      { label: "Mengabaikan dan membiarkan rumus error `#N/A` di dashboard", score: 0 },
    ],
  },
  {
    id: "da-metrics-1",
    careerId: "data-analyst",
    type: "TECHNICAL",
    skillId: "business-metrics",
    text: "Apa definisi dari Customer Acquisition Cost (CAC) dalam metrik performa bisnis?",
    options: [
      { label: "Total biaya marketing & penjualan dibagi dengan jumlah pelanggan baru yang didapat dalam periode tersebut", score: 100 },
      { label: "Harga jual produk dikurangi harga pokok produksi", score: 20 },
      { label: "Jumlah komplain pelanggan yang masuk ke WhatsApp admin", score: 0 },
      { label: "Gaji staf admin dalam satu tahun berjalan", score: 10 },
    ],
  },
  {
    id: "da-stat-1",
    careerId: "data-analyst",
    type: "TECHNICAL",
    skillId: "statistics",
    text: "Kapan nilai Median lebih representatif daripada Mean (rata-rata) untuk menggambarkan ukuran pemusatan?",
    options: [
      { label: "Saat data memiliki skewness tinggi atau terdapat nilai pencilan ekstrem (outlier)", score: 100 },
      { label: "Saat data terdistribusi simetris sempurna", score: 20 },
      { label: "Saat jumlah sampel data hanya 2 baris", score: 10 },
      { label: "Median tidak pernah lebih baik dari nilai mean", score: 0 },
    ],
  },
  {
    id: "da-eda-1",
    careerId: "data-analyst",
    type: "TECHNICAL",
    skillId: "eda",
    text: "Apa fokus utama tahapan Exploratory Data Analysis (EDA) dalam sebuah proyek analitik?",
    options: [
      { label: "Menemukan pola distribusi data, anomali, korelasi awal, dan menguji asumsi dasar data", score: 100 },
      { label: "Langsung meluncurkan model deep learning ke server produksi", score: 10 },
      { label: "Menulis artikel blog opini marketing", score: 0 },
      { label: "Menghapus tabel database asli tanpa backup", score: 0 },
    ],
  },
  {
    id: "da-report-1",
    careerId: "data-analyst",
    type: "TECHNICAL",
    skillId: "reporting",
    text: "Bagaimana cara menyusun dashboard analitik yang efektif untuk pemilik UMKM?",
    options: [
      { label: "Fokus pada KPI actionable utama, visualisasi bersih mudah dicerna, dan sertakan kesimpulan rekomendasi bisnis", score: 100 },
      { label: "Menampilkan 50 tabel raw data dalam satu layar penuh tanpa grafik ringkasan", score: 10 },
      { label: "Menggunakan warna neon berkedip di seluruh penjuru halaman", score: 0 },
      { label: "Hanya menyajikan angka rumus matematika tanpa label nama kolom", score: 0 },
    ],
  },
  {
    id: "ss-problem-3",
    careerId: "data-analyst",
    type: "SOFT_SKILL",
    skillId: "problem-solving",
    text: "Saat angka omzet di dashboard analitik berbeda dengan uang kas fisik toko UMKM, apa yang Anda lakukan?",
    options: [
      { label: "Melakukan rekonsiliasi data: memeriksa transaksi retur, biaya admin payment gateway, dan audit pencatatan", score: 100 },
      { label: "Mengubah manual angka di database agar cocok dengan saldo kas tanpa bukti", score: 0 },
      { label: "Menyalahkan kasir toko di depan umum tanpa data pendukung", score: 0 },
      { label: "Menganggap perbedaan data sebagai hal lumrah yang tak perlu dicari penyebabnya", score: 10 },
    ],
  },
  {
    id: "ss-comm-3",
    careerId: "data-analyst",
    type: "SOFT_SKILL",
    skillId: "communication",
    text: "Bagaimana cara mempresentasikan insight data ke pemilik UMKM yang awam istilah statistika?",
    options: [
      { label: "Fokus pada cerita bisnis: dampak keuntungan, produk paling laris, dan langkah konkrit yang perlu diambil toko", score: 100 },
      { label: "Membacakan seluruh rumus p-value dan standar deviasi secara mendalam", score: 10 },
      { label: "Mengirimkan file spreadsheet mentah tanpa memberi kesimpulan apapun", score: 0 },
      { label: "Menggunakan bahasa yang meremehkan latar belakang pendidikan pemilik usaha", score: 0 },
    ],
  },
  {
    id: "ss-digital-3",
    careerId: "data-analyst",
    type: "SOFT_SKILL",
    skillId: "digital-literacy",
    text: "Bagaimana menjaga privasi data pelanggan UMKM (PII - Personally Identifiable Information) saat mengolah data?",
    options: [
      { label: "Melakukan anonimisasi/masking pada nomor telepon, email, dan alamat sebelum melakukan analisis atau ekspor data", score: 100 },
      { label: "Mengunggah data mentah pelanggan ke forum publik online untuk meminta bantuan", score: 0 },
      { label: "Menjual daftar kontak pelanggan ke pihak ketiga untuk uang tambahan", score: 0 },
      { label: "Menyimpan file spreadsheet pelanggan di komputer umum tanpa password", score: 0 },
    ],
  },

  // ── Digital Marketer (10 Technical + 3 Soft Skills) ───────
  {
    id: "dm-seo-1",
    careerId: "digital-marketer",
    type: "TECHNICAL",
    skillId: "seo",
    text: "Elemen on-page SEO apa yang paling krusial untuk halaman produk UMKM?",
    options: [
      { label: "Title tag relevan kata kunci, meta deskripsi menarik, heading hierarkis, dan konten deskripsi orisinil", score: 100 },
      { label: "Menjejali kata kunci yang sama sebanyak 200 kali di dasar halaman (keyword stuffing)", score: 0 },
      { label: "Memasang banner iklan pop-up berkedip", score: 0 },
      { label: "Mengganti URL halaman setiap 2 hari sekali", score: 0 },
    ],
  },
  {
    id: "dm-content-1",
    careerId: "digital-marketer",
    type: "TECHNICAL",
    skillId: "content-strategy",
    text: "Apa fungsi menyusun Content Pillar dalam strategi pemasaran media sosial?",
    options: [
      { label: "Menjaga konsistensi tema konten (edukasi, hiburan, promosi, testimoni) yang selaras dengan target persona audiens", score: 100 },
      { label: "Membuat semua postingan hanya berisi promo jualan 'Beli Sekarang Diskon 50%'", score: 10 },
      { label: "Menghindari kebutuhan posting terjadwal", score: 0 },
      { label: "Meniru 100% konten kompetitor tanpa modifikasi", score: 0 },
    ],
  },
  {
    id: "dm-ads-1",
    careerId: "digital-marketer",
    type: "TECHNICAL",
    skillId: "meta-ads",
    text: "Kapan penggunaan Custom Audience (retargeting) di Meta Ads paling efektif?",
    options: [
      { label: "Saat ingin menyasar orang yang sudah berinteraksi dengan profil toko atau menambahkan barang ke keranjang belanja", score: 100 },
      { label: "Saat menyasar seluruh penduduk Indonesia tanpa filter minat usia", score: 10 },
      { label: "Ketika tidak memiliki produk atau jasa untuk ditawarkan", score: 0 },
      { label: "Hanya saat beriklan di koran fisik cetak", score: 0 },
    ],
  },
  {
    id: "dm-ga-1",
    careerId: "digital-marketer",
    type: "TECHNICAL",
    skillId: "google-analytics",
    text: "Bagaimana cara kerja tracking traffic kampanye di Google Analytics 4 (GA4) secara akurat?",
    options: [
      { label: "Memasang UTM Parameters (utm_source, utm_medium, utm_campaign) pada setiap tautan promosi", score: 100 },
      { label: "Hanya mengira-ngira dari jumlah like di postingan Instagram", score: 10 },
      { label: "Menghapus cookie browser pengguna sebelum mereka mengklik link", score: 0 },
      { label: "GA4 tidak mendukung tracking sumber kunjungan link", score: 0 },
    ],
  },
  {
    id: "dm-copy-1",
    careerId: "digital-marketer",
    type: "TECHNICAL",
    skillId: "copywriting",
    text: "Apa alur formula copywriting AIDA yang terbukti meningkatkan konversi penjualan?",
    options: [
      { label: "Attention (perhatian) -> Interest (minat) -> Desire (keinginan) -> Action (ajakan bertindak)", score: 100 },
      { label: "Argue -> Ignore -> Delete -> Apologize", score: 0 },
      { label: "Always -> Inspect -> Data -> Always", score: 10 },
      { label: "Action -> Action -> Action -> Action", score: 10 },
    ],
  },
  {
    id: "dm-social-1",
    careerId: "digital-marketer",
    type: "TECHNICAL",
    skillId: "social-media",
    text: "Metrik mana yang paling menunjukkan retensi dan daya tarik konten video pendek (Reels / TikTok)?",
    options: [
      { label: "Average watch time (retensi durasi tonton) dan jumlah shares/saves", score: 100 },
      { label: "Hanya total views di 3 detik pertama saja", score: 30 },
      { label: "Jumlah hashtag yang dipasang di kolom caption", score: 10 },
      { label: "Warna latar belakang thumbnail video", score: 10 },
    ],
  },
  {
    id: "dm-email-1",
    careerId: "digital-marketer",
    type: "TECHNICAL",
    skillId: "email-marketing",
    text: "Apa praktik terbaik dalam email marketing agar tidak dianggap sebagai SPAM oleh penyedia email?",
    options: [
      { label: "Mendapatkan consent opt-in resmi dari audiens dan menyediakan tombol unsubscribe yang jelas di footer", score: 100 },
      { label: "Membeli database 100.000 email acak lalu mengirim pesan massal sekaligus", score: 0 },
      { label: "Menggunakan subject tulisan kapital semua 'MENANG HADIAH RATUSAN JUTA'", score: 0 },
      { label: "Menyembunyikan identitas pengirim email", score: 0 },
    ],
  },
  {
    id: "dm-market-1",
    careerId: "digital-marketer",
    type: "TECHNICAL",
    skillId: "market-research",
    text: "Bagaimana cara membuat Buyer Persona yang relevan untuk produk UMKM lokal?",
    options: [
      { label: "Merumuskan demografi, masalah utama (pain points), tujuan, dan media yang sering digunakan target pembeli", score: 100 },
      { label: "Menargetkan semua manusia dari umur 5 tahun sampai 80 tahun tanpa diferensiasi", score: 10 },
      { label: "Hanya berpatokan pada selera pribadi pemasar semata", score: 10 },
      { label: "Membeli ulasan palsu di marketplace", score: 0 },
    ],
  },
  {
    id: "dm-perf-1",
    careerId: "digital-marketer",
    type: "TECHNICAL",
    skillId: "performance-metrics",
    text: "Sebuah kampanye iklan menghabiskan Rp 1.000.000 dan menghasilkan penjualan bersih Rp 5.000.000. Berapa nilai ROAS-nya?",
    options: [
      { label: "5x (atau 500%)", score: 100 },
      { label: "1x (atau 100%)", score: 10 },
      { label: "0.2x (atau 20%)", score: 20 },
      { label: "Rp 4.000.000", score: 30 },
    ],
  },
  {
    id: "dm-cro-1",
    careerId: "digital-marketer",
    type: "TECHNICAL",
    skillId: "conversion-rate",
    text: "Apa langkah optimasi conversion rate (CRO) tercepat jika banyak pengunjung masuk ke landing page namun tidak membeli?",
    options: [
      { label: "Memperbaiki kejelasan penawaran (value prop), menambah bukti ulasan sosial (social proof), dan menyederhanakan tombol CTA", score: 100 },
      { label: "Menambah 15 formulir isian wajib yang panjang", score: 0 },
      { label: "Menaikkan harga barang 3 kali lipat", score: 0 },
      { label: "Menghapus nomor kontak customer support", score: 0 },
    ],
  },
  {
    id: "ss-problem-4",
    careerId: "digital-marketer",
    type: "SOFT_SKILL",
    skillId: "problem-solving",
    text: "Ketika iklan berbayar mengalami penurunan performa (ad fatigue / ROAS turun), langkah evaluasi Anda?",
    options: [
      { label: "Menguji variasi materi kreatif visual baru, merotasi copy headline, dan menguji audiens segar", score: 100 },
      { label: "Langsung menaikkan budget harian 10x lipat tanpa mengubah materi iklan", score: 0 },
      { label: "Menyalahkan algoritma platform dan menghentikan seluruh promosi toko", score: 10 },
      { label: "Membuat klaim berlebihan yang menyesatkan konsumen", score: 0 },
    ],
  },
  {
    id: "ss-comm-4",
    careerId: "digital-marketer",
    type: "SOFT_SKILL",
    skillId: "communication",
    text: "Bagaimana cara menyajikan laporan mingguan performa marketing kepada pemilik UMKM?",
    options: [
      { label: "Menyampaikan ringkasan biaya yang dikeluarkan vs pendapatan yang dihasilkan beserta saran taktik minggu depan", score: 100 },
      { label: "Hanya membanggakan impressions jutaan tanpa menyebutkan ada penjualan atau tidak", score: 10 },
      { label: "Tidak mengirimkan laporan jika hasilnya sedang kurang memuaskan", score: 0 },
      { label: "Mengubah angka penjualan di laporan agar terlihat sukses", score: 0 },
    ],
  },
  {
    id: "ss-digital-4",
    careerId: "digital-marketer",
    type: "SOFT_SKILL",
    skillId: "digital-literacy",
    text: "Apa prinsip etika periklanan digital yang wajib dipatuhi pemasar profesional?",
    options: [
      { label: "Jujur dalam menyampaikan klaim khasiat/keunggulan produk dan tidak melakukan clickbait penipuan", score: 100 },
      { label: "Memasang testimoni palsu hasil editan Photoshop", score: 0 },
      { label: "Menjelek-jelekkan merek kompetitor lokal secara anonim", score: 0 },
      { label: "Menggunakan bot spam di kolom komentar influencer lain", score: 0 },
    ],
  },
];

export function getQuestionsForCareer(careerId: CareerDomainId | string): AssessmentQuestion[] {
  return ASSESSMENT_QUESTIONS.filter((q) => q.careerId === careerId);
}

export function getTechnicalQuestions(careerId: CareerDomainId | string): AssessmentQuestion[] {
  return ASSESSMENT_QUESTIONS.filter(
    (q) => q.careerId === careerId && q.type === "TECHNICAL",
  );
}

export function getSoftSkillQuestions(careerId: CareerDomainId | string): AssessmentQuestion[] {
  return ASSESSMENT_QUESTIONS.filter(
    (q) => q.careerId === careerId && q.type === "SOFT_SKILL",
  );
}
